### PR TITLE
Scan and store secret references on SECRET_REFERENCE cluster variables

### LINKED ISSUE #58931: [Secret Resolution] Scan & store secret references in SECRET_REFERENCE cluster variable values
### 

### Description

On cluster-variable create/update, when `kind == SECRET_REFERENCE`, scan the value for embedded `camunda.secrets.<name>` references and store them (value sub-pointer + name) on the `ClusterVariableRecord`. Detected once on the origin partition and carried across partitions — create carries the refs on the distributed command value; update carries them by extending `applyUpdate` to copy them onto the stored record.

### Motivation

Second of the three pieces of #56559. A `SECRET_REFERENCE` cluster variable's value embeds `camunda.secrets.*` placeholders; recording which secrets a variable contains (and where in its value) is what lets the job-creation join fold them onto a job. Storing on create/update keeps the lookup cheap at job creation and makes the references available to other consumers.

### Acceptance criteria

- [ ] `SECRET_REFERENCE` values scanned on create and update; `JSON` kind never scans
- [ ] References stored on the record; update replaces them (a value updated from secrets to none ends up empty)
- [ ] Carried deterministically to the distributed partition (no re-scan on the receiver)
- [ ] Backwards compatible (new optional msgpack property, empty default, pre-8.10); golden regenerated
- [ ] Unit tests

### Links

Sub-issue of #56559. Part of #56555. Builds on #57920. Independent of the input-mapping-detection sub-issue; prerequisite for the job-join sub-issue.

### Breakdown

- New `ClusterVariableSecretReference` protocol value (mirror `JobSecretReference`) + `secretReferences` array on `ClusterVariableRecord`.
- Value scanner: `camunda.secrets.<name>` string leaves → (value sub-pointer, name).
- Wire into `ClusterVariableCreateProcessor` (origin) and `ClusterVariableUpdateProcessor` (origin scan + `applyUpdate` copies the refs). Event appliers unchanged.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Second of the three pieces of #56559. When a `SECRET_REFERENCE` cluster variable is created or updated, this scans the value for embedded `camunda.secrets.<name>` references and stores them on the `ClusterVariableRecord` — the secret name plus the RFC 6901 JSON pointer of the leaf it was found in. Doing it at write time keeps the eventual job-creation lookup cheap: the scan runs once on the origin partition and the result rides the distributed command/event to the other partitions unchanged, so receivers never re-scan. `JSON`-kind variables are never scanned.

A couple of things worth calling out:
1. On update the `kind` is read from the stored record (the update command may omit it), and `applyUpdate` copies the references onto the stored record with a reset-then-add — so a value updated from secrets to none ends up empty rather than accumulating stale references.
2. Both cluster-variable exporter index templates are `dynamic: strict`, so I extended them with the new `secretReferences` mapping in the same change — otherwise the new field would break the exporter.

The protocol value and record property mirror the existing `JobSecretReference` feature. The new msgpack property is an empty-by-default array, so it's backwards compatible and the golden was regenerated. Consumption (folding these references onto a job at creation) is the next sub-issue and out of scope here.

Implemented by Claude against a plan I reviewed; unit tests (scanner behavior, create/update scanning, single- and multi-partition carry) and the golden regeneration are included.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).
- [ ] If this PR modifies the [C8 Orchestration Cluster E2E Test Suite](qa/c8-orchestration-cluster-e2e-test-suite), the relevant tests have been run via the [on-demand workflow](https://github.com/camunda/camunda/actions/workflows/c8-orchestration-cluster-e2e-tests-on-demand.yml) before requesting review. Any test failures are documented in the PR description and confirmed not to be regressions introduced by this PR.

## Related issues

closes #58931

### CODE REVIEW

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/clustervariable/ClusterVariableRecord.java [hunk 1]
```diff
@@ -145,4 +153,68 @@ public boolean isTenantScoped() {
...
+              copy.copy(element);
+              return (ClusterVariableSecretReferenceValue) copy;
+            })
+        .toList();
+  }
+
+  public ClusterVariableRecord setSecretReferences(
+      final List<? extends ClusterVariableSecretReferenceValue> secretReferences) {
+    secretReferencesProp.reset();
+    if (secretReferences != null) {
```
Comment (remcowesterhoud) [inline zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/clustervariable/ClusterVariableRecord.java]: ❌ This can never be `null`. Check is not needed.

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/clustervariable/ClusterVariableRecord.java [hunk 2]
```diff
@@ -145,4 +153,68 @@ public boolean isTenantScoped() {
...
+        .setStoreId(storeId)
+        .setSecretReference(secretReference)
+        .setPath(path);
+    return this;
+  }
+
+  public ClusterVariableRecord resetSecretReferences() {
+    secretReferencesProp.reset();
+    return this;
+  }
```
Comment (remcowesterhoud) [inline zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/clustervariable/ClusterVariableRecord.java]: ❌ I don't think we should expose the reset to the outside world. This class should decide when it needs to reset and control this behavior.

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/clustervariable/ClusterVariableSecretReference.java [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+    setPath(secretReference.getPath());
+  }
+
+  /** Copies the values buffer-to-buffer, avoiding the String round-trip of {@link #copy}. */
+  public ClusterVariableSecretReference copyFrom(final ClusterVariableSecretReference other) {
+    storeIdProp.setValue(other.getStoreIdBuffer());
+    secretReferenceProp.setValue(other.getSecretReferenceBuffer());
+    pathProp.setValue(other.getPathBuffer());
+    return this;
+  }
```
Comment (remcowesterhoud) [inline zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/clustervariable/ClusterVariableSecretReference.java]: ❌ Naming-wise we normally call this `wrap`

File: zeebe/protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java [hunk 4]
```diff
@@ -3500,7 +3501,40 @@ final var record = new ClockRecord().offsetBy(30);
...
+                  "tenantId": "<default>",
+                  "metadata": {},
+                  "kind": "SECRET_REFERENCE",
+                  "secretReferences": [
+                    {
+                      "storeId": "",
+                      "secretReference": "token",
+                      "path": "/auth"
+                    }
+                  ]
```
Comment (remcowesterhoud) [inline zeebe/protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java]: ❌ Instead of making this another case, can you just add it to an existing one. Normally we have 2 scenarios per record. One with nothing poopulated but the required fields and one with everything populated. Refactor cluster variables to this pattern if required.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableCreateProcessor.java [hunk 5]
```diff
@@ -64,6 +68,9 @@ public void processNewCommand(final TypedRecord<ClusterVariableRecord> command)
         .flatMap(clusterVariableRecordValidator::validateUniqueness)
         .ifRightOrLeft(
             record -> {
+              if (clusterVariableRecord.getKind() == ClusterVariableKind.SECRET_REFERENCE) {
+                applySecretReferences(clusterVariableRecord);
+              }
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableCreateProcessor.java]: 🔧 Can we make this a separate step in the chain?

```
clusterVariableRecordValidator
        .validateName(clusterVariableRecord)
        .flatMap(clusterVariableRecordValidator::ensureValidScope)
        .flatMap(record -> isAuthorized(record, command))
        .flatMap(clusterVariableRecordValidator::validateUniqueness)
        .flaMap(applySecretRefrences(record)
        .ifRightOrLeft(
        ....
```

You can do the if-check inside of the method to keep it clean.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableCreateProcessor.java [hunk 6]
```diff
@@ -101,6 +108,19 @@ final var record = command.getValue();
...
   }
 
+  /**
+   * Scans the record's value for secret references and sets them on the record. Only ever called on
+   * the origin partition ({@link #processNewCommand}): the resulting refs are set on the same
+   * record that is appended, returned in the accepted response, and distributed, so a receiver's
+   * {@link #processDistributedCommand} carries them without re-scanning.
+   */
+  private void applySecretReferences(final ClusterVariableRecord record) {
+    record.resetSecretReferences();
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableCreateProcessor.java]: It should be impossible at this time for secret references to be on the record. This reset shouldn't be necessary.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableSecretReferenceScanner.java [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+ * array elements) and recording each distinct reference name together with the RFC 6901 JSON
+ * pointer of the leaf it was found in.
+ *
+ * <p>This only detects references; resolving them into activated job variables is a separate, later
+ * concern (see the job-join sub-issue tracked under #56563).
+ */
+public final class ClusterVariableSecretReferenceScanner {
+
+  private static final Pattern SECRET_REFERENCE =
+      Pattern.compile("camunda\\.secrets\\.[\\p{Alnum}_]+");
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableSecretReferenceScanner.java]: ❓ Do you see a way to reuse this from `SecretReferenceLiteralValidator`? We now have a duplciated pattern. Maybe we can put it in the `zeebe-util` module somewhere?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableSecretReferenceScanner.java [hunk 8]
```diff
@@ -0,0 +1,103 @@
...
+  /**
+   * Scans the msgpack value buffer, returning every secret reference with its leaf's JSON pointer.
+   */
+  public List<DetectedReference> scan(final DirectBuffer valueBuffer) {
+    final JsonNode root;
+    try {
+      root = mapper.readTree(new DirectBufferInputStream(valueBuffer));
+    } catch (final IOException e) {
+      throw new UncheckedIOException(e);
+    }
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableSecretReferenceScanner.java:59]: ❌ Can we ensure this method returns an `Either` and exceptions get turned into a `Rejection`? That ensures we apply good error reporting back to the user.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableUpdateProcessor.java [hunk 9]
```diff
@@ -60,7 +64,16 @@ public void processNewCommand(final TypedRecord<ClusterVariableRecord> command)
...
         .flatMap(clusterVariableRecordValidator::loadExisting)
-        .map(stored -> applyUpdate(stored, commandRecord))
+        .map(
+            stored -> {
+              // kind is immutable-from-stored on update; the command may omit it, so scanning
+              // must key off the stored kind, not the (possibly absent) command kind
+              if (stored.getKind() == ClusterVariableKind.SECRET_REFERENCE) {
+                // set on the command record so the refs ride the distributed command to receivers
+                applySecretReferences(commandRecord);
+              }
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableUpdateProcessor.java]: 🔧 Can you put this in the `applyUpdate` method?

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableSecretReferenceTest.java [hunk 10]
```diff
@@ -0,0 +1,190 @@
...
+import io.camunda.zeebe.protocol.record.value.ClusterVariableRecordValue;
+import io.camunda.zeebe.protocol.record.value.ClusterVariableRecordValue.ClusterVariableSecretReferenceValue;
+import io.camunda.zeebe.test.util.record.RecordingExporterTestWatcher;
+import java.util.List;
+import java.util.Map;
+import org.junit.ClassRule;
+import org.junit.Rule;
+import org.junit.Test;
+
+public final class ClusterVariableSecretReferenceTest {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableSecretReferenceTest.java:25]: ❌ Pleae have a look at io.camunda.zeebe.engine.processing.deployment.model.element.SecretReferenceTest and ensure we cover all the same scenarios.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableUpdateProcessor.java [hunk 11]
```diff
@@ -99,10 +103,35 @@ record ->
     commandDistributionBehavior.acknowledgeCommand(command);
   }
 
+  /**
+   * For a SECRET_REFERENCE-stored variable, scans the command's value for secret references and
+   * sets them on the command record before applying the update; a non-SECRET_REFERENCE variable
+   * skips the scan. Kind is immutable-from-stored on update (the command may omit it), so scanning
+   * keys off the stored kind, not the (possibly absent) command kind. Only ever called on the
+   * origin partition ({@link #processNewCommand}), on the command record: the resulting refs then
+   * ride the distributed command, and the receiver's {@link #processDistributedCommand} copies them
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableUpdateProcessor.java]: ❓ Why does the distirbuted command need to apply the update anyway? Why doesn't it receive all the updated properties on the distributed record and simply writes an updated event after checking the cluster variable exists?

**Comment by remcowesterhoud** [comment]
@HeleneW-dot Would you mind reviewing this? I snuck in a small refactor in the final commit. Let me know if you prefer this being pulled into a separate PR instead.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableSecretReferenceScanner.java [hunk 12]
```diff
@@ -0,0 +1,103 @@
...
+
+/**
+ * Scans a SECRET_REFERENCE cluster variable's msgpack value for {@code camunda.secrets.<name>}
+ * occurrences, walking every string leaf of the value (the root scalar, object field values, and
+ * array elements) and recording each distinct reference name together with the RFC 6901 JSON
+ * pointer of the leaf it was found in.
+ *
+ * <p>This only detects references; resolving them into activated job variables is a separate, later
+ * concern (see the job-join sub-issue tracked under #56563).
+ */
```
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableSecretReferenceScanner.java:34]: I do not think we need to reference an issue here at all.

File: zeebe/exporters/elasticsearch-exporter/src/main/resources/elasticsearch/zeebe-record-cluster-variable-template.json [hunk 13]
```diff
@@ -39,6 +39,19 @@
             },
             "metadata": {
               "enabled": false
+            },
+            "secretReferences": {
```
Comment (berkaycanbc) [inline zeebe/exporters/elasticsearch-exporter/src/main/resources/elasticsearch/zeebe-record-cluster-variable-template.json:43]: ❌ Adding a field to the exported `ClusterVariableRecord` means an 8.9-broker record still in the export backlog gets serialized with `secretReferences` into an index the 8.9 exporter already created, whose strict mapping has no such field, so the exporter stalls (the same failure `JobMixin` was added for in a4318d2d915). This is not introduced here: `metadata` and `kind` already have the identical exposure on main, so a `ClusterVariableRecordValue` previous-version mixin covering all three, plus a `CLUSTER_VARIABLE` case in `BulkIndexRequestTest` and a cluster variable in the exporter migration ITs (which never create one today), fits better as its own follow-up than as something this PR carries.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableUpdateProcessor.java [hunk 14]
```diff
@@ -60,7 +64,7 @@ public void processNewCommand(final TypedRecord<ClusterVariableRecord> command)
     clusterVariableRecordValidator
         .ensureValidScope(commandRecord)
         .flatMap(clusterVariableRecordValidator::loadExisting)
-        .map(stored -> applyUpdate(stored, commandRecord))
+        .flatMap(stored -> applyUpdateWithSecretReferences(stored, commandRecord))
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableUpdateProcessor.java:68]: 🔧 The scan runs before `isAuthorized` here, while the create processor authorizes first, so an unauthorized caller still pays for a full msgpack tree walk on the single-threaded stream processor. Moving `applyUpdateWithSecretReferences` after the authorization check would line the two processors up.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableCreateProcessor.java [hunk 15]
```diff
@@ -101,6 +106,27 @@ final var record = command.getValue();
...
+  private Either<Rejection, ClusterVariableRecord> applySecretReferences(
+      final ClusterVariableRecord record) {
+    if (record.getKind() != ClusterVariableKind.SECRET_REFERENCE) {
+      return Either.right(record);
+    }
+    return secretReferenceScanner
+        .scan(record.getValueBuffer())
+        .map(
+            references -> {
+              references.forEach(ref -> record.addSecretReference("", ref.name(), ref.pointer()));
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableCreateProcessor.java:125]: 🔧 Nothing caps the number of detected references, so a large value densely packed with them can grow the follow-up event past the batch record size. Because the command record is mutated in place, the record used for the rejection is the grown one too, which is the case `Engine.handleUnexpectedError`'s empty-reason comment guards against; capping the count with an explicit rejection would surface a usable error instead of `EXCEEDED_BATCH_RECORD_SIZE` with no reason.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableUpdateProcessor.java [hunk 16]
```diff
@@ -99,11 +102,29 @@ record ->
...
+   * and secretReferences too, making it a complete stand-in for the merged record. That same
+   * command then rides the distribution, so the receiver's {@link #processDistributedCommand} only
+   * needs to confirm the variable still exists and can append the command record as-is.
+   */
+  private Either<Rejection, ClusterVariableRecord> applyUpdateWithSecretReferences(
       final ClusterVariableRecord stored, final ClusterVariableRecord command) {
-    stored.setValue(command.getValueBuffer());
-    stored.setMetadata(command.getMetadataBuffer());
-    return stored;
+    command.setKind(stored.getKind());
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableUpdateProcessor.java:117]: 🔧 With the stored-record merge gone this is the only field recovered from state, so the polarity flipped: before, a field not copied from the command kept its stored value; now, a field not pinned here silently takes the command's default. A test that updates a variable and asserts every stored field the update command does not carry survives would fail loudly the next time a create-only field is added and the pin is missed.

File: zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ClusterVariableRecordValue.java [hunk 17]
```diff
@@ -90,4 +93,37 @@ public interface ClusterVariableRecordValue extends RecordValue, TenantOwned {
...
   }
+
+  /**
+   * Returns the secret references detected in a SECRET_REFERENCE value: for each {@code
+   * camunda.secrets.<name>} occurrence, the reference name and the RFC 6901 JSON pointer of the
+   * value leaf it was found in. Empty for JSON-kind variables. Defaults to an empty list.
+   *
+   * @return the secret references detected in this variable's value
+   */
+  List<ClusterVariableSecretReferenceValue> getSecretReferences();
```
Comment (berkaycanbc) [inline zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ClusterVariableRecordValue.java:104]: 💭 The javadoc says the value defaults to an empty list, but unlike the sibling `getKind()` this method has no `default` implementation. Adding `default List.of()` (or dropping the sentence) would make the two agree.

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/clustervariable/ClusterVariableSecretReference.java [hunk 18]
```diff
@@ -0,0 +1,100 @@
...
+
+  public void copy(final ClusterVariableSecretReferenceValue secretReference) {
+    setStoreId(secretReference.getStoreId());
+    setSecretReference(secretReference.getSecretReference());
+    setPath(secretReference.getPath());
+  }
+
+  /** Copies the values buffer-to-buffer, avoiding the String round-trip of {@link #copy}. */
+  public ClusterVariableSecretReference wrap(final ClusterVariableSecretReference other) {
```
Comment (berkaycanbc) [inline zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/clustervariable/ClusterVariableSecretReference.java]: 💭 `wrap` lost its only caller when `copySecretReferencesFrom` was dropped in fd25c9f, so it can go along with it.

File: zeebe/protocol-impl/src/test/resources/protocol/records/golden/ClusterVariableRecord.golden [hunk 19]
```diff
@@ -145,4 +153,51 @@ public class ClusterVariableRecord extends UnifiedRecordValue
...
+        .setSecretReference(secretReference)
+        .setPath(path);
+    return this;
+  }
+
+  /**
+   * Copies the values buffer-to-buffer, avoiding the String round-trip of {@link
+   * #addSecretReference}.
+   */
+  public ClusterVariableRecord copySecretReferencesFrom(final ClusterVariableRecord other) {
```
Comment (berkaycanbc) [inline zeebe/protocol-impl/src/test/resources/protocol/records/golden/ClusterVariableRecord.golden]: 💭 The golden still carries `copySecretReferencesFrom`, which fd25c9f removed from the source. `RecordGoldenFilesTest` only diffs field sets so CI stays green, but re-copying the source keeps the golden a faithful snapshot.

**Review by berkaycanbc — CHANGES_REQUESTED** [review]
Thanks for the PR @remcowesterhoud!🚀 Solid work on the scan-once-on-the-origin-and-carry design. Requested one change (export compatibility, and it is not introduced by this PR) plus three minor comments and three nitpicks.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableCreateProcessor.java (hunk 15 above)
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/clustervariable/ClusterVariableCreateProcessor.java:125]: I'm not concerned about this and will leave this as-is. Currently, this problem already exists when a user decides to use a really large value for a cluster variable.

In the end the chance of this happening is low and the impact is small. The creation (or update) of the cluster variable will fail. The customer will get a rejected command and knows that the cluster variable isn't created. The error message is a bit technical, but imo it's not worth fixing this here as we have this same scenario for pretty much all user-triggered commands.

**Review by berkaycanbc — APPROVED** [review]
LGTM👍
