### PR TITLE
fix: build zeebe-protocol from source before Optimize docker snapshot

### PR DESCRIPTION
**Pull request by lev-safro**
## Problem

The `deploy-optimize-docker-snapshot` CI job was failing with a compilation error after PR #54592 ("support request source in record metadata") was merged:

```
Error: /home/runner/work/camunda/camunda/optimize/backend/src/main/java/io/camunda/optimize/dto/zeebe/ZeebeRecordDto.java:[12,40] cannot find symbol
  symbol:   class ChannelType
  location: package io.camunda.zeebe.protocol.record
Error:  /home/runner/work/camunda/camunda/optimize/backend/src/main/java/io/camunda/optimize/dto/zeebe/ZeebeRecordDto.java:[117,10] cannot find symbol
  symbol:   class ChannelType
  location: class io.camunda.optimize.dto.zeebe.ZeebeRecordDto<VALUE,INTENT>
Error:  /home/runner/work/camunda/camunda/optimize/backend/src/main/java/io/camunda/optimize/dto/zeebe/ZeebeRecordDto.java:[116,3] method does not override or implement a method from a supertype
Error:  /home/runner/work/camunda/camunda/optimize/backend/src/main/java/io/camunda/optimize/dto/zeebe/ZeebeRecordDto.java:[121,3] method does not override or implement a method from a supertype
```

## Root Cause

PR #54592 added `ChannelType` to the Zeebe SBE protocol (`protocol.xml`) and updated `Record.java` and `ZeebeRecordDto.java` to reference `io.camunda.zeebe.protocol.record.ChannelType`. This class is **SBE-generated** at build time from `zeebe/protocol/src/main/resources/protocol.xml` — it only exists in the `zeebe-protocol` JAR after the module is compiled.

The `deploy-optimize-docker-snapshot` CI job builds Optimize with:

```
./mvnw install -f optimize -DskipTests -Dskip.docker -PskipFrontendBuild,runAssembly -T1
```

Using `-f optimize` treats `optimize/pom.xml` as the Maven root. Maven resolves the `zeebe-protocol` dependency (declared as `${project.version}`, i.e. a SNAPSHOT) from its remote/cached SNAPSHOT repository — it does **not** rebuild `zeebe-protocol` from source.

Combined with the Maven caching strategy in this repo (`aether.enhancedLocalRepository.split=true`), the SNAPSHOT JAR downloaded by Maven was built **before** PR #54592 was merged and therefore does not contain the SBE-generated `ChannelType` class. The Optimize compilation then fails because `ChannelType` cannot be resolved.

## Fix

Add a Maven step before the Optimize build that installs `zeebe/protocol` from source:

```
./mvnw install -pl zeebe/protocol -Dquickly
```

This generates `ChannelType` via SBE and installs the fresh JAR into the local Maven repository. Maven's local repository takes precedence over remote SNAPSHOTs, so the subsequent Optimize build resolves the up-to-date `zeebe-protocol` JAR containing `ChannelType`.

## Alternatives Considered

- **Bust the Maven cache**: Changing the cache key would force a full re-download on every run — expensive and doesn't address the structural issue of `-f optimize` not rebuilding protocol from source.
- **Rebuild all dependencies with `-am`**: Using `-pl optimize -am` from the root POM would rebuild every transitive dependency, far exceeding what's needed and significantly increasing build time.
- **Hand-write `ChannelType.java`**: Duplicating the SBE enum as a hand-written Java class would conflict with the SBE-generated class at build time and create a maintenance burden.

https://claude.ai/code/session_011EH4TzJHheGmZ9NEtnPYCM

---
_Generated by [Claude Code](https://claude.ai/code/session_011EH4TzJHheGmZ9NEtnPYCM)_

### CODE REVIEW

File: .github/workflows/ci.yml [hunk 1]
```diff
@@ -2263,6 +2263,10 @@ jobs:
         id: build-optimize-fe
         with:
           directory: ./optimize/client
+      - name: Build zeebe-protocol from source
+        uses: ./.github/actions/run-maven
+        with:
+          parameters: install -pl zeebe/protocol -Dquickly
```
Comment (tmetzke) [inline .github/workflows/ci.yml:2269]: ❓ Is this really the only relevant dependency that needs to build first? That feels like a band-aid for one specific error class that we now encountered.

Comment (tmetzke) [reply .github/workflows/ci.yml:2269]: Sure, it's very focused to fix this specific defect, but any other dependency that has an update can lead to the same issue again, no?

Comment (cmur2) [reply .github/workflows/ci.yml:2269]: I'm also wondering whether we need a more generic solution - or is `zeebe/protocol` the only shared interface?

Comment (tmetzke) [reply .github/workflows/ci.yml:2269]: I don't think it is (not 100% sure but ALMOST certain, top of my head)

**Comment by lev-safro** [comment]
## Can this happen to other dependencies?

Yes, but the risk varies by module. The failure pattern requires three conditions to align:

1. The module is an internal monorepo dep (`${project.version}`) **outside** the `-f optimize` build
2. Optimize directly imports a **new symbol** from it
3. That symbol is absent from the cached/remote SNAPSHOT JAR

The external monorepo deps Optimize uses, and their risk:

| Module | Maven path | Has generated sources | Risk |
|---|---|---|---|
| `zeebe-protocol` | `zeebe/protocol` | **Yes — SBE** | **High** (proven) |
| `zeebe-protocol-jackson` | `zeebe/protocol-jackson` | No | Medium — if new Jackson mixins for new record types are added and immediately used |
| `camunda-client-java` | `clients/java` | No, but depends on `zeebe-protocol` | Medium — new API surface that mirrors protocol changes |
| `camunda-search-client-connect` | `search/search-client-connect` | No | Low — stable interface, no protocol dependency |
| `camunda-search-client-plugin` | `search` | No | Low |

`zeebe-protocol` is highest risk because SBE generation can add entirely new classes (not just methods on existing ones), which is the hardest kind of staleness to detect.

---

## Options to generalize

### Option A — Status quo (this PR): build only `zeebe-protocol`

```yaml
- name: Build zeebe-protocol from source
  uses: ./.github/actions/run-maven
  with:
    parameters: install -pl zeebe/protocol -Dquickly
```

**Pros:** Minimal, fast (~10s extra), fixes the known failure  
**Cons:** Any future addition to the other deps would cause the same issue and require another hotfix

---

### Option B — Build all external monorepo deps explicitly

```yaml
- name: Build monorepo dependencies for Optimize from source
  uses: ./.github/actions/run-maven
  with:
    parameters: install -pl zeebe/protocol,zeebe/protocol-jackson,clients/java,search/search-client-connect,search -Dquickly
```

**Pros:** Comprehensive protection against the full class of problem  
**Cons:** The list must be kept in sync with Optimize's actual dependencies — if a new dep is added to Optimize and this list isn't updated, the problem silently reappears

---

### Option C — Replace `-f optimize` with a root-POM `-pl` build

```yaml
parameters: install -pl zeebe/protocol,zeebe/protocol-jackson,clients/java,search/search-client-connect,search,optimize -am -Dquickly -DskipTests -Dskip.docker -PskipFrontendBuild,runAssembly -T1
```

**Pros:** Maven's own dependency graph handles it — no manual list to maintain  
**Cons:** `-am` with `install` rebuilds **all** transitive dependencies of Optimize, which is a very large set and could significantly increase build time. Also breaks the `-f optimize` isolation that was presumably chosen intentionally.

---

## Recommendation

Option B is the sweet spot. The list of five modules is small and stable — these are foundational modules unlikely to change frequently. It gives full protection for ~30s of extra build time. A comment in the workflow explaining why these modules are listed makes it self-documenting. Option A (this PR) is the minimal targeted fix; Option B can be followed up as a separate improvement if desired.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: .github/workflows/ci.yml (hunk 1 above)
Comment (lev-safro) [reply .github/workflows/ci.yml:2269]: @cmur2 @tmetzke I added more details in the comment below.

Comment (tmetzke) [reply .github/workflows/ci.yml:2269]: We could still start with this tight scope because it's the most likely one and expand if needed later, to avoid pulling in everything directly. There's always pros and cons 🤷

Comment (tmetzke) [reply .github/workflows/ci.yml:2269]: Ah, missed you update, @lev-safro, thanks for that 👍

**Review by tanjinyi — APPROVED** [review]
LGTM! I am still in the middle of backporting the dependent PRs. Once I am done, I will proceed to backport this to 8.8/8.9.

**Comment by lev-safro** [comment]
@cmur2 @tanjinyi shall I merge the `Option A` or do we want to proceed with `Option B / C`
